version: 2.1
orbs:
  node: circleci/node@5.1.0
  browser-tools: circleci/browser-tools@1.4.4
commands:
  build:
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn-berry
      - run:
          name: build packages
          command: yarn build:packages
executors:
  default:
    docker:
      - image: cimg/node:lts-browsers
    resource_class: large

jobs:
  lint:
    executor: default
    steps:
      - build
      - run:
          name: Lint
          command: yarn lint
  unit-test:
    executor: default
    steps:
      - build
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          name: Unit test
          command: yarn test:ci

workflows:
  test:
    jobs:
      - lint
      # - unit-test # TODO uncomment when fixed https://github.com/CircleCI-Public/browser-tools-orb/issues/90
