version: 2.1
orbs:
  node: circleci/node@5
  browser-tools: circleci/browser-tools@1
  cypress: cypress-io/cypress@3
commands:
  build:
    steps:
      - checkout
      - run: sudo corepack enable
      - node/install-packages:
          pkg-manager: yarn-berry
      - run:
          name: build packages
          command: yarn build:packages
executors:
  default:
    docker:
      - image: cimg/node:lts-browsers
    resource_class: large

jobs:
  lint:
    executor: default
    steps:
      - build
      - run:
          name: Lint
          command: yarn lint
  unit-test:
    executor: default
    steps:
      - build
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          name: Unit test
          command: yarn test:ci
  e2e:
    executor: default
    steps:
      - build
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - cypress/run-tests:
          start-command: yarn start
          cypress-command: yarn dlx wait-on https://localhost:4200 && yarn cypress:run
  build-app:
    executor: default
    steps:
      - build
      - run:
          name: Build App
          command: yarn build

workflows:
  test:
    jobs:
      - lint
      - build-app
      # - unit-test
      # - e2e
